### PR TITLE
Bundle ID name will be hidden if it is too long, tooltip will appear to display full name

### PR DESCRIPTION
**Pull request by MaksymShokin**
@tonytlwu @squallstar 

## Issue
Fliplet/fliplet-studio#4668

## Description
Limited max length on the bundle ID input to 155 chars. Added bootstrap tooltip. Bundle ID name will be hidden if it is too long.

## Screenshots/screencasts
bundle text demo

## Backward compatibility
This change is fully backward compatible.

### CODE REVIEW

**Comment by tonytlwu** [comment]
@MaksymShokin The screenshot made me realise that because the popover appears immediately, it becomes quite redundant for most users who have short bundle IDs. It's just the same bundle ID appearing over the same thing.

So, let's not use the popover. Instead, just use add `title` attribute so that if the user hovers over the bundle ID for long enough, it'll display the full bundle ID.

**Comment by MaksymShokin** [comment]
@tonytlwu Maybe a better solution would be showing tooltip only if it is longer then 45 chars. Also, we can add a delay. 
text-demo-over

**Comment by tonytlwu** [comment]
@MaksymShokin Excellent. Yes, let's go with both your suggestions please.

**Comment by MaksymShokin** [comment]
@tonytlwu Fixed. 
New look:
bundleid demo

**Pull request merged**
